ALTER TABLE "Clip" ADD COLUMN IF NOT EXISTS "rawClipUrl" TEXT;
ALTER TABLE "Clip" ADD COLUMN IF NOT EXISTS "renderedClipUrl" TEXT;
ALTER TABLE "Clip" ADD COLUMN IF NOT EXISTS "transcript" JSONB;
ALTER TABLE "Clip" ADD COLUMN IF NOT EXISTS "hook" TEXT;
ALTER TABLE "Clip" ADD COLUMN IF NOT EXISTS "start" DOUBLE PRECISION;
ALTER TABLE "Clip" ADD COLUMN IF NOT EXISTS "end" DOUBLE PRECISION;

CREATE INDEX IF NOT EXISTS "Clip_rawClipUrl_idx" ON "Clip" ("rawClipUrl");
